run:

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - testifylint

linters:
  disable-all: true
  enable:
    - gocyclo
    - govet
  presets:
    - bugs
    - unused
    - format

linters-settings:
  gocyclo:
    min-complexity: 15
  errcheck:
    exclude-functions:
      - fmt.Fprintln
      - io.Copy
      - (*net/http.ResponseWriter).Write
      - (io.ReadCloser).Close
