version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.41
    ports:
      - "16686:16686"
      - "4317:4317"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
